

# Authenticate
POST http://localhost:8022/elpatoclip/authenticate/tiktok
Content-Type: application/json

{
  "code": "",
  "redirectUrl": "https://clip.elpato.dev"
}

###

# Verify token
POST http://localhost:8022/token/verify
Content-Type: application/json

{
  "token": ""
}