

# Authenticate
POST http://localhost:8022/elpatoclip/authenticate/tiktok
Content-Type: application/json

{
  "code": "",
  "redirectUrl": "https://clip.elpato.dev"
}

###

# Verify token
POST http://localhost:8022/token/verify
Content-Type: application/json

{
  "token": "secret"
}


###

# Credential authentication
POST http://localhost:8022/testApp/authenticate
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123"
}

###

# Add user credentials
POST http://localhost:8022/testApp/createPasswordAuthenticatedUser
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123"
}